# Tokyo Night Light

# Cursor
cursor            #343b58
cursor_text_color #e6e7ed

# Background and Foreground
background #e6e7ed
foreground #343b58

# Selection
selection_background #b7c1e3
selection_foreground #343b58

# URL
url_color #2959aa

# Tab Bar
active_tab_foreground   #343b58
active_tab_background   #c4c8da
inactive_tab_foreground #6c6e75
inactive_tab_background #d8dae3
tab_bar_background      #d8dae3

# Normal colors
color0 #343b58
color1 #8c4351
color2 #385f0d
color3 #8f5e15
color4 #2959aa
color5 #5a3e8e
color6 #0f4b6e
color7 #828594

# Bright colors
color8  #6c6e75
color9  #8c4351
color10 #385f0d
color11 #8f5e15
color12 #2959aa
color13 #5a3e8e
color14 #0f4b6e
color15 #343b58

