# CMYK Light palette for Wayle. Filename is the theme name in the settings GUI.
# https://wayle.app/guide/themes
bg = "#c3c3c3"
surface = "#f6f5f4"
elevated = "#fdffff"

fg = "#130e0f"
fg_muted = "#00ebeb"

primary = "#00ebeb"

red = "#ef15bf"
yellow = "#ebef15"
green = "#00ebeb"
blue = "#00ebeb"
