# Basic settings
# font_family      JetBrains Mono
font_family      VCR OSD Mono
bold_font        auto
italic_font      auto
font_size        16.0

confirm_os_window_close 0

cursor_shape     block
bell_on_tab      no

# Theme
include current-theme.conf

# Window padding
window_padding_width 12
window_padding_height 16

