# Basic settings
# font_family      JetBrains Mono
font_family      VCR OSD Mono
bold_font        auto
italic_font      auto
font_size        16.0
# VCR OSD Mono has no emoji glyphs.
symbol_map U+2300-U+23FF,U+2600-U+27BF,U+2B00-U+2BFF,U+FE00-U+FE0F,U+1F000-U+1FAFF Noto Color Emoji

confirm_os_window_close 0

cursor_shape     block
bell_on_tab      no

# Theme
include current-theme.conf

# Window padding
window_padding_width 12
window_padding_height 16

