export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source "$ZSH/oh-my-zsh.sh"

[[ -f "$HOME/.una/aliases.sh" ]] && source "$HOME/.una/aliases.sh" >/dev/null
[[ -f "$HOME/.una/functions.sh" ]] && source "$HOME/.una/functions.sh" >/dev/null

if [[ -d "$HOME/AppImages" && ":$PATH:" != *":$HOME/AppImages:"* ]]; then
  export PATH="$HOME/AppImages:$PATH"
fi
if [[ -d "$HOME/.config/una/bin" && ":$PATH:" != *":$HOME/.config/una/bin:"* ]]; then
  export PATH="$HOME/.config/una/bin:$PATH"
fi
if [[ -f "$HOME/.cargo/env" ]]; then
  source "$HOME/.cargo/env"
fi
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.deno/bin:$PATH"

export EDITOR="vim"

[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
